#Python version
FROM python:3.10.9

#Working Directory
WORKDIR /code

#copy files into container at /code
COPY ./requirements.txt /code/requirements.txt

#Install the requirements
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

#Set up new user
RUN useradd user

#Switch to user
USER user

#Set home to the user's home directory
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

#Set the working directory to the user home directory
WORKDIR $HOME/app


#Copy the current directory contents into the container at $HOME/app
COPY --chown=user . $HOME/app

#Start FAST API
CMD ["uvicorn", "app:app","--host","0.0.0.0","--port","8080"]